# Build workflow gets auto triggered whenever a change to the file a.txt is merged to release branch

name: Release

on:
  push:
    tags:
    - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          GPG_PASSPHRASE: GPG_KEY
      - name: Publish package
        run: |
           echo "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
           echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
           mvn -B deploy -Prelease-sign-artifacts
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
